export enum ROLES_ENUM {
  ADMIN = 'ADMIN',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  FOLLOW_UP_OFFICER = 'FOLLOW_UP_OFFICER',
  HR_OFFICER = 'HR_OFFICER',
  SECURITY_LEADER = 'SECURITY_LEADER',
  SECURITY_MEMBER = 'SECURITY_MEMBER',
}
