export enum ValidationErrorKeyEnum {
  REQUIRED = 'required',
  AR_NUM = 'AR_NUM',
  ENG_NUM = 'ENG_NUM',
  MIN_LENGTH = 'minlength',
  MAX_LENGTH = 'maxlength',
  MIN = 'min',
  MAX = 'max',
  START_AFTER_END = 'startAfterEnd',
  TIME_FROM_AFTER_TIME_TO = 'timeFromAfterTimeTo',
  EMAIL = 'email',
  STRONG_PASSWORD = 'strongPassword',
  NATIONAL_ID = 'NATIONAL_ID',
  PHONE_NUMBER = 'PHONE_NUMBER',
  FAX = 'FAX',
  POSITIVE_NUMBER = 'positiveNumber',
  INVALID_NUMBER = 'invalidNumber',
  NUMBER_RANGE = 'numberRange',
  PASSWORD_MISMATCH = 'passwordMismatch',
}
