export enum ValidationErrorKeyEnum {
  REQUIRED = 'required',
  AR_NUM = 'AR_NUM',
  ENG_NUM = 'ENG_NUM',
  MIN_LENGTH = 'minlength',
  MAX_LENGTH = 'maxlength',
  MIN = 'min',
  MAX = 'max',
  PAST_DATE = 'pastDate',
  START_AFTER_END = 'startAfterEnd',
  TIME_FROM_AFTER_TIME_TO = 'timeFromAfterTimeTo',
  TIME_RANGE_SHOULD_CROSS_DAY = 'timeRangeShouldCrossDay',
  TIME_FROM_AND_TO_ARE_EQUAL = 'timeFromAndToAreEqual',
  EMAIL = 'EMAIL',
  STRONG_PASSWORD = 'strongPassword',
  NATIONAL_ID = 'NATIONAL_ID',
  PHONE_NUMBER = 'PHONE_NUMBER',
  FAX = 'FAX',
  POSITIVE_NUMBER = 'positiveNumber',
  INVALID_NUMBER = 'invalidNumber',
  NUMBER_RANGE = 'numberRange',
  PASSWORD_MISMATCH = 'passwordMismatch',
  DATE_MAX_RANGE_EXCEEDED = 'maxRangeExceeded',
  DUPLICATE_SHIFT = 'duplicateShift',
  SHIFTING_PERIOD_MAX_ONE_YEAR = 'shiftingPeriodMaxOneYear',
  INVALID_SHIFT_CONFIGURATION = 'invalidShiftConfiguration',
  GRACE_MONTHLY_LESS_THAN_DAILY = 'graceMonthlyMinutesLessThanDaily',
}
