export const Config = {
  VERSION: 'v0.0.1',
  BASE_ENVIRONMENT: '',
  ENVIRONMENTS_URLS: {},
  BASE_URL: '',
  API_VERSION: 'v1',
  DEPLOY_VERSION: '1.0.3',
  EXTERNAL_PROTOCOLS: ['http', 'https'],
  TOKEN_HEADER_KEY: 'Authorization',
  MIN_BEFORE_BUFFER: 10,
  MIN_AFTER_BUFFER: 10,
  MAX_BEFORE_BUFFER: 180,
  MAX_AFTER_BUFFER: 180,
  DAY_BOUNDARY_BEFORE_START_SHIFT_TIME_WITH: 240,
  DEV_VARIABLES: { INTEGRATION1: '', INTEGRATION2: '' },
  TEST_VARIABLES: { INTEGRATION1: '', INTEGRATION2: '' },
};

export type ConfigType = typeof Config;
