export const EndPoints = {
  BASE_URL: '',
  EXAMPLES: '/examples',
  PAGINATED_EXAMPLES: '/paginatedExamples',
  AUTH: '/auth',
  RESET_PASSWORD: '/PasswordReset',
  CITIES: 'cities',
  NATIONALITIES: '/nationalities',
  PERMISSION_REASONS: '/permissionreasons',
  ATTENDANCE: '/attendance',
  USERS: '/userprofiles',
  REGIONS: '/regions',
  NOTIFICATION_SETTINGS: '/notificationsettings',
  DEPARTMENTS: '/departments',
  HOLIDAYS: '/holidays',
  PERMISSION_TYPES: '/permissiontypes',
  PERMISSION_STATUS: '/permissionstatuses',
  PERMISSIONS: '/permissions',
  SHIFTS: '/shifts',
  NOTIFICATION: '/notifications',
  User_Work_Shifts: '/UserWorkShifts',
  NOTIFICATION_TYPES: '/notificationtypes',
  WORK_MISSION: '/WorkMission',
};

export type EndpointsType = typeof EndPoints;
