name: Deploy Angular to SmarterASP.NET via FTP

on:
  push:
    branches:
      - testing # Trigger when code is merged to testing branch

jobs:
  build_and_deploy:
    runs-on: windows-latest
    environment: mujdn-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --output-path=dist

      - name: Deploy to SmarterASP.NET via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.MUJDN_BACK_SERVER_IP }}
          username: ${{ secrets.MUJDN_BACK_SERVER_USERNAME_DEVFRONT }}
          password: ${{ secrets.MUJDN_BACK_SERVER_PASSWORD }}
          server-dir: /m-front/
          local-dir: ./dist/
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.github*
